name: Update README

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README.md
      run: |
        # Get all image files in the wallpapers directory
        IMAGES=$(ls Wallbash/*.{jpg,jpeg,png,gif} 2>/dev/null || true)

        # Start creating the new content for README
        CONTENT="# Wallpaper Library\n\n## Available Wallpapers\n\n"

        if [ -n "$IMAGES" ]; then
          for IMAGE in $IMAGES; do
            # Append image markdown to the content
            CONTENT+="![]($IMAGE)  \n"
          done
        else
          CONTENT+="No wallpapers available.\n"
        fi
        
        # Write content to README.md
        echo -e "$CONTENT" > README.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with new wallpapers" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/0xRad1ant/WallBash.git HEAD:main
